version: '3.9'

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - cicd-network
    restart: unless-stopped

networks:
  cicd-network:
    external: true
    name: tp2_cicd-network
